name: Build and test njcode-webpage

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build:ssr

    - name: Test Angular App
      run: npm run test:ci
